### ISSUE TITLE
Items are pale

### ISSUE THREAD

**Issue by Terravolt14** [RCXcrafter/Materialis#1]
The items seem to be white for me and I don't know why

**Comment by RCXcrafter** [comment]
I'm not sure what's causing this, for now you can reload all assets with F3+T to fix it until I have fixed it.

**Comment by KiraLinux** [comment]
using F3 + T it is very painful to reboot an assembly with 160 mod

**Comment by RCXcrafter** [comment]
I realize that reloading assets can take a lot of time and memory, which is why I want to fix this as soon as possible, but I'm not sure how soon I'll be able to fix it.

**Comment by RCXcrafter** [comment]
fixed in version 1.2.1
