### ISSUE TITLE
Mod Support Suggestion for 1.16.5

### ISSUE THREAD

**Issue by ModernGamingWorld** [RCXcrafter/Materialis#10]
BetterEnd Forge(Thallasium, Terminite, and Aeternium)
DruidCraft(Moonstone)
Botania (Manasteel, Elementium, and Terrasteel)
Applied Energistics 2 (Certus Quartz and Fluix)
Twilight Forest
Refined Storage
Mystical Agriculture

**Comment by ManInTheMists** [comment]
Blood Magic has a "Forbidden ingot" that is currently unused, but perhaps could have a use from this mod.  Weapons with a Forbidden part would work like a sentient sword, making slain critters drop will and possibly gaining damage bonuses from having a tartaric gem with high will.

**Comment by RCXcrafter** [comment]
I've decided to create a new issue for suggestions #12 so I will close this one, I've added these suggestions to the list.
