### ISSUE TITLE
Crash with new TiCon version

### ISSUE THREAD

**Issue by Lgmrszd** [RCXcrafter/Materialis#11]
Game crashes when trying to load with latest version of TiCon.
I had other mods around but I'm sure this is not the case here.

Crash report: https://gist.github.com/Lgmrszd/121f213de021aacdc9cc447f6b5c6dd1

### Versions:
TiCon: 1.16.5-3.1.1.252
Materialis: 1.16.5-2.0.1
Forge: 36.2.0

**Comment by RCXcrafter** [comment]
This happens because the tinkers construct api changed, I will release a new version of materialis soon that uses the lastest version of the api.

**Comment by NillerMedDild** [comment]
I hope you don't mind me asking, but do you have a rough estimate for when the update will be? Are we talking a few days, weeks? :)

**Comment by RCXcrafter** [comment]
I'm hoping to release it today, if not it will be tomorrow

**Comment by NillerMedDild** [comment]
Awesome, thanks!
