### ISSUE TITLE
Can not work with Tinkers' Construct 3.2.0.290 for 1.16.5

### ISSUE THREAD

**Issue by magcicada** [RCXcrafter/Materialis#14]
Can not work with TC version 1.16.5-3.2.0.290,
This is the changelog of TC 3.2.0.290:

- `Breaking changes`

- `These changes will only affect addons that add new tools. If the addon does not add new tools, it should continue to work as before.`

- `Tool definition build is now done through datapacks, so the old builders no longer exist. There was no clean way to keep the old builds and migrate to datapacks.`

- `Code calling methods on tool definitions should still work, though many old methods are deprecated.`

- `The old Tinker Station Slot layout logic was removed, so JSON added for slots will no longer work.`

- `There are no breaking changes in code as all the related classes were not in the API.`

**Comment by RCXcrafter** [comment]
I am aware that the latest tinkers construct build breaks materialis, I've been following the development of tinkers construct and I'm almost ready to release the next version of materialis.

**Comment by RCXcrafter** [comment]
fixed in version 2.2.0
