### ISSUE TITLE
[1.18.2][Suggestion] Material checkbox

### ISSUE THREAD

**Issue by ffuentesm** [RCXcrafter/Materialis#19]
Would be nice if added an individual materia compatibility checkbox in the settings?
So we can turn off a specific material compatibility. I mostly asking that since some mods add the same material compatibility with different stats and this way you could be able to choose which to pick.
Like how Tinker's Reforged and Materialis both add aluminum.

I also had the same problem back in 1.16.5 where different mods coffered the same popular material, such as Manasteel or Livingwood.

**Comment by KnightMiner** [comment]
Note you can disable materials using datapacks, materials are just JSON files. I suspect most of Materialis's materials have a condition already, you can use the condition type `forge:false` to make it always disable.

**Comment by ffuentesm** [comment]
is possible to add that as a config menu option or it only works if I do it manually?

**Comment by RCXcrafter** [comment]
There is no menu for this, you have to make a datapack. I believe it can also be done with crafttweaker and kubejs since they can mimic datapacks.
