### ISSUE TITLE
[1.18.2] Livingwood Log is not being recognised as part material

### ISSUE THREAD

**Issue by ffuentesm** [RCXcrafter/Materialis#20]
materialis-1.18.2-2.5.3.jar
TConstruct-1.18.2-3.5.0.17.jar

The livingwood material is only accepting the twig, but not logs, or planks. 
![image](https://user-images.githubusercontent.com/44974827/170903850-f1613fa2-c36d-4d09-b180-b166df05a632.png)

Logs are being seen as normal wood
![image](https://user-images.githubusercontent.com/44974827/170903565-9bf2c3fe-5660-4c7d-b330-a83b8dde6a37.png)

**Comment by RCXcrafter** [comment]
fixed in materialis 2.6.0
