### ISSUE TITLE
Items will randomly not stack

### ISSUE THREAD

**Issue by CritFlaw** [RCXcrafter/Materialis#21]
Doing a binary search through [my modpack](https://www.curseforge.com/minecraft/modpacks/modblend-2/files) I isolated the issue to this mod.
Sticks, cobblestone, really any item will at random times have stacks that refuse to merge. Usually it happens when you have a given stack or single item in your hand and try to get more of it through a storage drawer or harvesting. 

There doesn't appear to be any NBT data that is different on either stack, and it can somewhat be mitigated by somehow in-game modifying (placeable sticks when broken will merge again) or dropping the items in-world to have them merge naturally on the ground if they complete up to a stack (you drop two stacks that are up to 64 and they will merge). 

Details:
Forge - 40.1.25
Minecraft - 1.18.2
Materialis - 2.6.0

**Comment by RCXcrafter** [comment]
That was a pretty silly mistake with some pretty big consequences, fixed in version 2.6.1
For the record, this happens when you punch a block, which explains why it was happening with storage drawers.

**Comment by CritFlaw** [comment]
It was happening with harvested crops as well, not sure if that's the same thing. Not punching to harvest, the quark right click to harvest.

**Comment by RCXcrafter** [comment]
That might be because it's breaking the crop and instantly replanting it, I'm not sure about that though.
