### ISSUE TITLE
Crash after entering a world

### ISSUE THREAD

**Issue by castilio20** [RCXcrafter/Materialis#27]
The game crash after you enter a world on when you try to enter a world
[crash-2023-05-23_12.12.12-client.txt](https://github.com/RCXcrafter/Materialis/files/11542259/crash-2023-05-23_12.12.12-client.txt)

**Comment by DeshiDesu** [comment]
[crash-2023-05-26_18.04.39-client.txt](https://github.com/RCXcrafter/Materialis/files/11580229/crash-2023-05-26_18.04.39-client.txt)
I have a similar report, but the crash happened while exploring

Forge 40.2.4
MC 1.18.2
materialis-1.18.2-2.8.0.jar

**Comment by RCXcrafter** [comment]
Fixed in version 2.8.1
