### ISSUE TITLE
Crash introduced when used with Create 5.1b

### ISSUE THREAD

**Issue by Nihilhalla** [RCXcrafter/Materialis#28]
[latest.log](https://github.com/RCXcrafter/Materialis/files/11595369/latest.log)
[crash-2023-05-29_23.18.35-client.txt](https://github.com/RCXcrafter/Materialis/files/11595370/crash-2023-05-29_23.18.35-client.txt)

Crash occurs when hovering over plated/slimewood tools in either an inventory or JEI.
Immersive engineering appears in the stacktrace but is latest version with no indication of issues before we updated to Create 5.1b.
TConstruct, Materialis, Mantle, Create, and JEI versions are all latest at time of writing, specific versions are in the crash log.

If you need additional information please don't hesitate to ask.

**Comment by RCXcrafter** [comment]
Fixed in version 2.8.1
