### ISSUE TITLE
[1.18.2] IllegalStateException when opening/closing inventory

### ISSUE THREAD

**Issue by Secretname2009** [RCXcrafter/Materialis#29]
Im reporting this bug as is since this randomly crashes the game.
Minecraft 1.18.2 with Forge 40.2.9
Using Materialis 1.18.2-2.8.4 with TConstruct 1.18.2-3.6.4.113
This bug only occurs when i open my inventory or close it and it happends only on clientside.
[crash-2023-06-04_12.39.25-client.txt](https://github.com/RCXcrafter/Materialis/files/11645416/crash-2023-06-04_12.39.25-client.txt)

I will provide more information if neccesary.

**Comment by RCXcrafter** [comment]
Materialis version 2.8.1 and above only works with create 0.5.1 or above, update create or downgrade materialis to 2.8.0

**Comment by Secretname2009** [comment]
I didnt know Materialis was affected by the newest update to Create. Thanks for letting me know. Some mods are still not updated to support Create >0.5.1 so im stuck below that version.

**Comment by RCXcrafter** [comment]
Yeah it's pretty annoying to deal with mods changing their api mid-minecraft version
