### ISSUE TITLE
Fairy unable to alloy (Materialis & Tinkers') // Materialis-1.18.2-2.8.5 | TConstruct-1.18.2-3.6.4.113

### ISSUE THREAD

**Issue by Under031** [RCXcrafter/Materialis#30]
For some reason, when all necessary materials and heating fluid are provided, Molten Fairy is unable to alloy inside a smeltery.
Either that, or there is another material that does not show up in JEI's alloying screen that is required for alloying Molten Fairy.
I suspect it is the latter of the two. I will also post this to JEI's and Tinker's issue forum, as it may be a problem on their end.
![Minecraft_ 1 18 2 - Singleplayer 6_11_2023 7_43_57 PM](https://github.com/RCXcrafter/Materialis/assets/128875931/99c1dc6c-127a-4c8d-8e3f-23f9faf7dc41)

**Comment by Under031** [comment]
JEI issue.

**Comment by RCXcrafter** [comment]
This is not a jei issue, this happened because I switched to using the forge tag for molten soulsand which is never actually registered.

**Comment by RCXcrafter** [comment]
fixed in version 2.8.6
