### ISSUE TITLE
[1.18.2] Crash - Cannot fetch a static modifiers before modifiers are registered

### ISSUE THREAD

**Issue by Gogo08190** [RCXcrafter/Materialis#31]
Hello,

When I want to go in the search icon from creative inventory my modpack crash instantly..
I have the same crash when I want to click on the icon from Tinkers planner

I have this crash report : https://pastebin.com/8wqhux4A

When I removed materialis from my modpack, I don't have any crashes.

Informations :
Minecraft version : 1.18.2
Forge version : Forge - 40.2.4
TConstruct version : 3.6.4.113
Materialis version : 2.8.6

**Comment by RCXcrafter** [comment]
This is because create changed their api, update create to 0.5.1 or downgrade materialis to 2.8.0
