### ISSUE TITLE
Galvanized doesn't remove upgrade slots [1.18.2 - 2.8.6]

### ISSUE THREAD

**Issue by Gebcrafter** [RCXcrafter/Materialis#32]
![image](https://github.com/RCXcrafter/Materialis/assets/15183529/80e9832a-a271-4871-98a7-bbb036899153)
A normal iron pickaxe (3 upgrades) and a custom tool part with Galvanized I (galvanized seen on the right). It just ends up with an extra ability slots with no downside. I checked and, yes, you can use all 3 upgrade slots. I do not have whichever mod would normally add tools with Galvanized, I'm just using it in a custom datapack, so forgive me if this is a known issue.

**Comment by RCXcrafter** [comment]
The galvanized modifier is intended to be a counterpart to the gilded modifier. Just like with gilded, the modifier itself does not actually remove slots, the recipe for the modifier is intended to do that. Unfortunately that means it won't work as expected when used as a trait.
