### ISSUE TITLE
Exception thrown, causing crash.

### ISSUE THREAD

**Issue by 120ace** [RCXcrafter/Materialis#7]
Hello, I have encountered an error between Materialis and Tinkers' Evolution (https://www.curseforge.com/minecraft/mc-mods/tinkers-evolution).
During startup your mod attempts to register tin to Tinkers and throws an exception because Tcon Evolution has already registered it.

Installed Mods:
  Tinkers' Construct.
  Mantle.
  Materialis.
  Tinkers' Evolution.
  Libnine.
  BioLib.
Crash Report: https://pastebin.com/mTRwP3Mt

Thanks.

**Comment by RCXcrafter** [comment]
To fix conflicting materials, simply blacklist the conflicting material in the config for one of the mods
